# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_extended_0.82.0_Linux-64bit.deb
  displayName: 'Download Hugo'

- script: sudo dpkg -i hugo.deb
  displayName: 'Install Hugo'

- script: hugo version
  displayName: 'check hugo version'
  
- script: hugo -D
  displayName: 'build site'
